export const icons = {
  arrow_back: require('../../assets/icons/arrow_back.png'),
  arrow_down: require('../../assets/icons/arrow_down.png'),
  checbox_outline: require('../../assets/icons/checbox_outline.png'),
  checbox_tick: require('../../assets/icons/checbox_tick.png'),
  close: require('../../assets/icons/close.png'),
  company: require('../../assets/icons/company.png'),
  delete: require('../../assets/icons/delete.png'),
  document: require('../../assets/icons/document.png'),
  download: require('../../assets/icons/download.png'),
  duplicate: require('../../assets/icons/duplicate.png'),
  edit: require('../../assets/icons/edit.png'),
  more: require('../../assets/icons/more.png'),
  notifications: require('../../assets/icons/notifications.png'),
  profile: require('../../assets/icons/profile.png'),
  share: require('../../assets/icons/share.png'),
  sort: require('../../assets/icons/sort.png'),
  tick: require('../../assets/icons/tick.png'),
}
